/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rainbow.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rainbow(props) {
  const { nodes, materials } = useGLTF('/images/Rainbow.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rainbow_Circle010_1.geometry} material={materials.F44336} />
      <mesh geometry={nodes.Rainbow_Circle010_1_1.geometry} material={materials.FF5722} />
      <mesh geometry={nodes.Rainbow_Circle010_1_2.geometry} material={materials.FF9800} />
      <mesh geometry={nodes.Rainbow_Circle010_1_3.geometry} material={materials['4CAF50']} />
      <mesh geometry={nodes.Rainbow_Circle010_1_4.geometry} material={materials['039BE5']} />
      <mesh geometry={nodes.Rainbow_Circle010_1_5.geometry} material={materials['673AB7']} />
      <mesh geometry={nodes.Rainbow_Circle010_1_6.geometry} material={materials.FFFFFF} />
    </group>
  )
}

useGLTF.preload('/images/Rainbow.glb')
